### ISSUE TITLE
ros_readbagfile.py: running in python3

### ISSUE THREAD

**Issue by leehayford** [ElectricRCAircraftGuy/eRCaGuy_dotfiles#9]
ros_readbagfile.py runs in Python3.8.2, with only two changes.

Changed line 1:
was > #!/usr/bin/python2
now > #!/usr/bin/python3

Changed line 135:
was > if msg_counters.has_key(topic) == False:
now > if topic not in msg_counters:

[SeeComment](https://github.com/ElectricRCAircraftGuy/eRCaGuy_dotfiles/commit/e5fe3111cb8a25715cee5829bcb5a163a14e4def#commitcomment-43451869)

**Comment by ElectricRCAircraftGuy** [comment]
Thanks @leehayford .
